/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package top.klw8.alita.dubbodoc.annotations;

import java.lang.annotation.*;

/**
 * @author klw(213539 @ qq.com)
 * @ClassName: RequestParam
 * @Description: Dimension request parameter
 * @date 2020/2/2 13:35
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Documented
@Inherited
public @interface RequestParam {

    /**
     * @author klw(213539@qq.com)
     * @Description: param name
     */
    String value();

    /**
     * @author klw(213539@qq.com)
     * @Description: required
     */
    boolean required() default false;

    /**
     * @author klw(213539@qq.com)
     * @Description: description(HTML tags available)
     */
    String description() default "";

    /**
     * @author klw(213539@qq.com)
     * @Description: example(HTML tags available)
     */
    String example() default "";

    /**
     * @author klw(213539@qq.com)
     * @Description: default value
     */
    String defaultValue() default "";

    /**
     * @author klw(213539@qq.com)
     * @Description: Allowed values. After setting this property, a drop-down list will be generated for the parameter <br />
     * Note: a drop-down selection box will be generated after using this property<br />
     * 1. Parameters of boolean type do not need to be set with this property. A drop-down list of true / false will be generated by default<br />
     * 2. Parameters of enumeration type will automatically generate a drop-down list. If you do not want to open all enumeration values, you can set this property separately.
     */
    String[] allowableValues() default {};

}
