dubbo:
  registry:
    address: spring-cloud://localhost
  provider:
    timeout: 2000
  protocol:
    port: 20882
    name: dubbo
spring:
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true